services:
  db:
    image: postgres:15
    container_name: mysawit
    restart: always
    environment:
      POSTGRES_DB: mysawit
      POSTGRES_USER: mysawit
      POSTGRES_PASSWORD: penyakitsawitgila
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: