name: Java CI with Gradle

on:
  push:
    branches: [ "main", "staging", "feat/*" ]
  pull_request:
    branches: [ "main", "staging" ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: mysawit
          POSTGRES_USER: mysawit
          POSTGRES_PASSWORD: penyakitsawitgila
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U mysawit"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build, Test & Lint
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/mysawit
          SPRING_DATASOURCE_USERNAME: mysawit
          SPRING_DATASOURCE_PASSWORD: penyakitsawitgila
        run: ./gradlew clean build check --configuration-cache

      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/mysawit
          SPRING_DATASOURCE_USERNAME: mysawit
          SPRING_DATASOURCE_PASSWORD: penyakitsawitgila
        run: ./gradlew sonar --configuration-cache -Dsonar.qualitygate.wait=true
